#!/bin/bash
STEP=${STEP:-stepA_mal}
CLOJURE=$(which clojure)
BABASHKA=$(which bb)

NAMESPACE=mal.steps.${STEP//_/-}

#echo Main namespace: $NAMESPACE

if [ "${CLOJURE}" != "" ]; then
  #echo Using Clojure CLI at $CLOJURE
  exec ${CLOJURE} -M -m ${NAMESPACE} "${@}"
else
  #echo Using Babashka at $BABASHKA
  exec ${BABASHKA} -f $(dirname $0)/src/mal/steps/${STEP}.clj \
    -m mal.steps.${STEP//_/-} \
    "${@}"
fi

